name: Build Python Application
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_python_application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          if [ -f requirements.txt ]; then pip install -f requirements.txt; fi
      - name: Run flake8
        run: flake8
      - name: Run pytest
        run: pytest