name: Include/Exclude Matrix
on: [push]
jobs:
  include_exclude_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [16, 18, 20]
        include:
          - os: ubuntu-latest
            node_version: 20
            ubuntu_20: true
          - os: macos-latest
            node_version: 20
            ubuntu_20: false
          - os: windows-latest
            node_version: 20
            ubuntu_20: false
        exclude:
          - os: ubuntu-latest
            node_version: 16
          - os: macos-latest
            node_version: 18
    runs-on: ${{ matrix.os }}
    env:
      UBUNTU_20: ${{ matrix.ubuntu_20 }}
    steps:
      - name: Current node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: After setup node with different version
        run: |
          node -v
          echo $UBUNTU_20