name: Setup Node Js with version
on:
  push:
    branches: [main]
jobs:
  install_specific_nodejs_version:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [16, 18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Display current node js version
        run: |
          hostname
          node -v
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: node js version after installation
        run: |
          hostname
          node -v
