name: Schedule Event Workflow # Name of the workflow
on:
  schedule:
    - cron: '0/1 * * * *' # Schedule event on specific time

jobs:
  hello_world: # Job name
    runs-on: ubuntu-latest # Use this image to craete container
    steps:
      - name: Display current date
        run: echo "At present date is $(date)" 
