name: Self host runner from AWS # create ec2 instance with inbound and outbound opens with http/https ports 80,443
on: [push]
jobs:
  self-hosted-runner:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: |
          cd src
          python -m addition.py
          python -m pytest