name: Webhook event example
on:
  repository_dispatch:
    types:
      - webhook

jobs:
  external_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Display event name
        run: 'echo "Event of type $GITHUB_EVENT_NAME "'

# Use below curl request to do POST request
# curl -X POST \
# -H "Accept: application/vnd.github+json" \
# -H "Authorization: token github_pat_11BOTFB6A004CPjNWCvzXQ_n1DEMOWnEsMqiSFem27Ycql8xM71c5Mp5IhtgqP134NONRNACOTT207Zjk7" \
# -d '{"event_type": "webhook", "client_payload": {"key": "value"} }' \
# https://api.github.com/repos/Veeravarapu-Saikiran/Github-Actions/dispatches